### ISSUE TITLE
Consider adding a timeout for `mamba install`

### ISSUE THREAD

**Issue by pentschev** [rapidsai/gha-tools#129]
This isn't a case I've seen frequently, in fact it is something I've seen for the first time in [this run](https://github.com/rapidsai/ucx-py/actions/runs/12387890462/job/34578058418). For some reason, that one particular `mamba install` never completed (but rerunning worked), and due to that a GPU runner was there idle for 6h until hitting GHA's timeout.

I suggest adding a "safe" timeout to install commands such as `rapids-mamba-retry`, obviously it cannot be too short, but perhaps a somewhat high timeout such as 30m or 60m would prevent this from happening again while still being broadly safe for all our repos.

**Comment by jameslamb** [comment]
Thanks for opening this. Adding some details.

Based on https://docs.conda.io/projects/conda/en/latest/configuration.html, I don't see a way to set a timeout on the entire install... just things like:

* `remote_connect_timeout_secs:` = timeout on connecting to package repositories (I think?)
* `remote_read_timeout_secs:` = timeout on reading data from package repositories

And I don't see any options in `conda install --help` to timeout the entire operation. Maybe @jakirkham or @msarahan would have other suggestions about how to put a time-limit on the total runtime of `{conda, mamba} install`.

I really think the failure you're pointing to was specifically during the *environment solve* (as I've seen similar things before), and so I agree that wrapping `{conda, mamba} install` in `timeout` is the best way to achieve what we want.

Also noting that if this is picked up, we'll have to be careful about the interplay with retries:

https://github.com/rapidsai/gha-tools/blob/9915e909b97f9b27c8f1bb84ec85457d3bae2957/tools/rapids-mamba-retry#L12-L18

e.g. there's a difference between "the entry `rapids-mamba-retry` operation should not take more than 30 minutes" and "no individual `mamba install` should take more than 30 minutes", and we'd have to pick which one we want.

**Comment by pentschev** [comment]
One more data point, this happened again yesterday [in this run](https://github.com/rapidsai/ucx-py/actions/runs/12617301739/job/35159435455).

**Comment by jameslamb** [comment]
I noticed today that in the RAPIDS docker images, we do exactly what @pentschev had recommended for this issue... wrapping `conda install` in `timeout`:

```shell
if [ -e "/home/rapids/environment.yml" ]; then
    echo "environment.yml found. Installing packages."
    timeout ${CONDA_TIMEOUT:-600} mamba env update -n base -f /home/rapids/environment.yml || exit $?
fi
```

([rapidsai / docker / context / entrypoint.sh](https://github.com/rapidsai/docker/blob/4f0424d40af9640cf61fd6d4653b5fa3b2b4bb52/context/entrypoint.sh#L11-L24))

I'll prepare a PR in `gha-tools` introducing a timeout.

**Comment by pentschev** [comment]
I'm starting to think there may be something with the 11.8, but it is happening again now with the (still at time of writing) running build: https://github.com/rapidsai/ucx-py/actions/runs/12646571173/job/35237499476

**Comment by jakirkham** [comment]
Let's try consolidating those 2 install steps into 1 step as we have done elsewhere. This has avoided odd solve situations as well. Submitted PR: https://github.com/rapidsai/ucx-py/pull/1101

**Comment by jakirkham** [comment]
> Let's try consolidating those 2 install steps into 1 step as we have done elsewhere. This has avoided odd solve situations as well. Submitted PR: [rapidsai/ucx-py#1101](https://github.com/rapidsai/ucx-py/pull/1101)

This is now done

**Comment by pentschev** [comment]
There's another ongoing nightly test, this time a [UCXX nightly](https://github.com/rapidsai/ucxx/actions/runs/12762476288/job/35571062408), that's running for almost 3h now. AFAIU, the changes that @jakirkham applied for UCX-Py are already [part of that test](https://github.com/rapidsai/ucxx/blob/b0027cf55130e2d1a2eada58d052cba6a0fd253e/ci/test_python_distributed.sh#L28), which seems to hint that we may still encounter the same sort of problems despite that.

Thoughts?

**Comment by jakirkham** [comment]
Think we need to roll out the same kind of changes for UCXX

We have a broader effort this is a part of: https://github.com/rapidsai/build-planning/issues/22

However given the nature of the changes, it winds up being somewhat custom for each project. So hasn't been amenable to our semiautomated tooling. Hence why this has been moving a bit slower

**Comment by pentschev** [comment]
Ah right, my bad, I misunderstood the problem, it's not downloading the cache but rather creating the environment with the proper package from the build step in one go. That is indeed not yet the case in UCXX, unfortunately I won't have much time to work on it before the 25.02 release.

In any case, the changes to create the environment immediately with the built packages are definitely welcome improvements, however, I still think the original ask _may_ be useful to prevent any issues from any unforeseen circumstances so that we don't block a GPU runner for 6h for no good reason. WDYT?

**Comment by jameslamb** [comment]
>  I still think the original ask may be useful to prevent any issues from any unforeseen circumstances

I absolutely agree and still plan to put up a PR adding a timeout mechanism around conda operations in `gha-tools`.

**Comment by pentschev** [comment]
[Here](https://github.com/rapidsai/dask-cuda/actions/runs/13106734295/job/36562909161) is one more sample this time on a docs build, so fortunately not a GPU runner.

**Comment by jameslamb** [comment]
@pentschev unfortunately that one actually WAS a GPU runner.

<img width="787" alt="Image" src="https://github.com/user-attachments/assets/e014a24c-0eab-4039-a818-668e8c3d9f54" />

Many RAPIDS projects run their docs builds on GPU runners, because of a mix of:

* `sphinx.ext.autosummary` and similar require running `import {project}`
* many RAPIDS libraries have a hard dependency on CUDA being available at runtime

Anyway, I'll have a PR up today proposing a timeout. I'm not super happy with the way the implementation is looking, but we can talk about that on the PR.

**Comment by pentschev** [comment]
Oh, I didn't notice it was a GPU runner. But even to build docs are we required to have CUDA imports? I presume it needs to collect information that's not easily inferred by static analysis? (Sorry for the lame question, I don't know much about sphinx internals)

**Comment by jameslamb** [comment]
I'm not sure if `sphinx.ext.autosummary` *could* figure out what it needs via static analysis, but it definitely *doesn't*.

`sphinx.ext.autosummary` imports modules to generate summaries of them, using `importlib.import_module()`:

https://github.com/sphinx-doc/sphinx/blob/758dc8130366bb2d8ae36c50c86e497c25970d82/sphinx/ext/autosummary/generate.py#L184

*(I think that's the relevant portion of the code)*

Anything anywhere in that import chain could end up bringing in a dependency on CUDA (including many RAPIDS libraries).

Try like this *(note the lack of `--gpus`, so `docker` cannot see the GPU)*:

```shell
docker run \
  --rm \
  -it rapidsai/base:25.02a-cuda12.8-py3.10-arm64 \
  python -c "import cuml; print(cuml.__version__)"
```

```text
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/opt/conda/lib/python3.10/site-packages/numba_cuda/numba/cuda/cudadrv/driver.py", line 314, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
```

For projects that are careful to be importable without a GPU, that's not a problem. For example `ucxx`:

```shell
docker run \
  --rm \
  -it rapidsai/base:25.02a-cuda12.8-py3.10-arm64 \
  python -c "import ucxx; print(ucxx.__version__)"
# 0.42.00
```

But that's not all/most RAPIDS libraries, so it's common to see a GPU runner used:

```yaml
docs-build:
  # ...
  uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-25.04
  with:
    # ...
    node_type: "gpu-l4-latest-1"
```

([cuml/.github/workflows/pr.yaml](https://github.com/rapidsai/cuml/blob/def265e8e852f749532b5ac590ab38738fb253a0/.github/workflows/pr.yaml#L173))

And I think that snippet has just been copied around multiple projects. I suspect that some projects, like `ucxx`, might be able to switch to CPU runners for their docs builds.

It does seem like `ucxx` and all its dependencies are installable from scratch without a GPU (so nothing anywhere in the dependency chain has a hard dependency on the `__cuda` virtual package):

```shell
docker run \
  --rm \
  -it rapidsai/ci-conda \
  /bin/bash -c 'conda install --yes ucxx==0.43.*; python -c "import ucxx; print(ucxx.__version__)"'
# 0.43.00
```

**Comment by vyasr** [comment]
Summarizing from some offline discussions, it is possible to address the imports piece in some cases, e.g. [by using mock imports in autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports), but we also often build notebooks that actually run the module so we need GPU runners for that.

**Comment by jameslamb** [comment]
Thanks for summarizing that here on GitHub!

For the main topic of this issue (timeouts), I have a proposal up for anyone who's interested: https://github.com/rapidsai/gha-tools/pull/140

(yes @bdice that means you can review now 😛 )

**Comment by pentschev** [comment]
> And I think that snippet has just been copied around multiple projects. I suspect that some projects, like ucxx, might be able to switch to CPU runners for their docs builds.

UCXX currently depends on RMM, so I'm not entirely sure that's the case today. I hope to at some point have time to work on ensuring UCXX has absolutely no CUDA dependencies, but it's low on my priority list for the time being.

**Comment by jameslamb** [comment]
I just merged #140. It'll be active in CI once this build completes: https://github.com/rapidsai/ci-imgs/actions/runs/13265559002
